name: Deploy to production

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast2
  REPOSITORY: baca-app-be
  IMAGE_NAME: baca-app-be
  VM_HOST: ${{ secrets.VM_HOST }}
  VM_USER: ${{ secrets.VM_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: SSH Deploy to Compute Engine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}

          envs: PROJECT_ID,REGION,REPOSITORY,IMAGE_NAME
          envs_format: |
            export PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}";
            export REGION="asia-southeast2";
            export REPOSITORY="baca-app-be";
            export IMAGE_NAME="baca-app-be";

          script: |
            IMAGE_TAG=${{ github.sha }}

            echo "Stopping old container..."
            docker stop app || true
            docker rm app || true

            echo "Pulling new image..."
            docker pull $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

            echo "Running new container..."
            docker run -d \
              --name app \
              -p 80:3000 \
              $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
